import { Service, Staff, Customer, Booking, Transaction, InventoryItem, SMSLog, Coupon } from "./types";

export const INITIAL_SERVICES: Service[] = [
  { id: "s1", name: "Premium Gel Manicure", category: "Gel", price: 45, durationMinutes: 45 },
  { id: "s2", name: "Organic Detox Pedicure", category: "Pedicure", price: 55, durationMinutes: 50 },
  { id: "s3", name: "Signature Combo (Mani + Pedi)", category: "Other", price: 85, durationMinutes: 90 },
  { id: "s4", name: "Acrylic Full Set (Nude/Gel)", category: "Acrylic", price: 65, durationMinutes: 75 },
  { id: "s5", name: "Acrylic Fill-In", category: "Acrylic", price: 40, durationMinutes: 50 },
  { id: "s6", name: "Nail Art Custom Design (2-10 fingers)", category: "Nail Art", price: 25, durationMinutes: 20 },
  { id: "s7", name: "Classic French Pedicure", category: "Pedicure", price: 45, durationMinutes: 40 },
  { id: "s8", name: "Eyebrow Waxing & Shaping", category: "Waxing", price: 18, durationMinutes: 15 },
  { id: "s9", name: "Gel Polish Color Change", category: "Gel", price: 25, durationMinutes: 20 },
];

export const INITIAL_STAFF: Staff[] = [
  { id: "st1", name: "Amber Nguyen", phone: "+1 (408) 555-0192", role: "Technician", rating: 4.9, commissionRate: 0.60, color: "#EC4899", avatar: "https://images.unsplash.com/photo-1544005313-94ddf0fb8004?w=150" },
  { id: "st2", name: "Johnny Tran", phone: "+1 (408) 555-0143", role: "Technician", rating: 4.8, commissionRate: 0.60, color: "#3B82F6", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150" },
  { id: "st3", name: "Lily Smith", phone: "+1 (408) 555-0154", role: "Technician", rating: 4.9, commissionRate: 0.55, color: "#10B981", avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150" },
  { id: "st4", name: "Tommy Le", phone: "+1 (408) 555-0177", role: "Technician", rating: 4.7, commissionRate: 0.60, color: "#F59E0B", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150" },
  { id: "st5", name: "Tina Pham", phone: "+1 (408) 555-0111", role: "Manager", rating: 5.0, commissionRate: 0.65, color: "#8B5CF6", avatar: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150" },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: "c1",
    name: "Jenny Nguyen",
    phone: "+1 (650) 441-2091",
    email: "jenny.nguyen@example.com",
    birthday: "1994-06-21",
    points: 480,
    tier: "Gold",
    notes: "Thích form móng almond, chỉ sơn màu nude hoặc gel nhẹ. Thích massage tay thêm.",
    visitCount: 12,
    totalSpent: 540,
    lastVisitDate: "2026-06-10",
  },
  {
    id: "c2",
    name: "Tiffany Cooper",
    phone: "+1 (650) 321-1182",
    email: "tiff.cooper@example.com",
    birthday: "1991-11-04",
    points: 850,
    tier: "Platinum",
    notes: "Dị ứng với dầu massage có hương cam chanh. Ưu tiên thợ Johnny Tran làm Acrylic móng dài.",
    visitCount: 18,
    totalSpent: 1120,
    lastVisitDate: "2026-06-15",
  },
  {
    id: "c3",
    name: "Sarah Miller",
    phone: "+1 (408) 223-9912",
    email: "sarah_m@example.com",
    birthday: "1988-03-15",
    points: 120,
    tier: "Silver",
    notes: "Thích móng vuông ngắn, chọn sơn thường vì dễ thay đổi.",
    visitCount: 4,
    totalSpent: 180,
    lastVisitDate: "2026-06-01",
  },
  {
    id: "c4",
    name: "David Vu",
    phone: "+1 (415) 880-1288",
    email: "davidvu88@example.com",
    birthday: "1985-08-30",
    points: 210,
    tier: "Silver",
    notes: "Chỉ làm Pedicure Organic. Cần cắt da thừa tỉ mỉ, thích ngâm muối thảo mộc ấm.",
    visitCount: 6,
    totalSpent: 330,
    lastVisitDate: "2026-05-28",
  },
  {
    id: "c5",
    name: "Elena Rostova",
    phone: "+1 (408) 771-4433",
    email: "elena_ros@example.com",
    birthday: "1999-01-12",
    points: 55,
    tier: "Bronze",
    notes: "Thích Nail Art hoa vẽ tay nổi bật. Da tay mỏng nhạy cảm dễ chảy máu, cẩn thận lúc dũa phao móng.",
    visitCount: 2,
    totalSpent: 95,
    lastVisitDate: "2026-06-18",
  },
  {
    id: "c6",
    name: "Chloe Davis",
    phone: "+1 (650) 901-7788",
    email: "chloe@davis-law.com",
    birthday: "1980-06-25", // Upcoming birthday!
    points: 1050,
    tier: "Platinum",
    notes: "Thích phòng vip tĩnh lặng, luôn tip cao cho Lily. Chỉ uống trà lài.",
    visitCount: 22,
    totalSpent: 1450,
    lastVisitDate: "2026-06-12",
  },
  {
    id: "c7",
    name: "Sophia Martinez",
    phone: "+1 (408) 334-0012",
    email: "sophia.mart@example.com",
    birthday: "1997-09-18",
    points: 30,
    tier: "Bronze",
    notes: "Khách mới, thích sơn gel ombre lấp lánh.",
    visitCount: 1,
    totalSpent: 45,
    lastVisitDate: "2026-06-14",
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  // Bookings for TODAY (2026-06-19)
  {
    id: "b1",
    customerId: "c1",
    customerName: "Jenny Nguyen",
    customerPhone: "+1 (650) 441-2091",
    serviceId: "s1",
    serviceName: "Premium Gel Manicure",
    staffId: "st1",
    staffName: "Amber Nguyen",
    dateTime: "2026-06-19T09:00:00",
    status: "Completed",
    price: 45,
    notes: "Màu nude nhạt thạch đào",
  },
  {
    id: "b2",
    customerId: "c2",
    customerName: "Tiffany Cooper",
    customerPhone: "+1 (650) 321-1182",
    serviceId: "s4",
    serviceName: "Acrylic Full Set (Nude/Gel)",
    staffId: "st2",
    staffName: "Johnny Tran",
    dateTime: "2026-06-19T10:30:00",
    status: "Completed",
    price: 65,
    notes: "Almond shape, long",
  },
  {
    id: "b3",
    customerId: "c5",
    customerName: "Elena Rostova",
    customerPhone: "+1 (408) 771-4433",
    serviceId: "s6",
    serviceName: "Nail Art Custom Design (2-10 fingers)",
    staffId: "st3",
    staffName: "Lily Smith",
    dateTime: "2026-06-19T13:00:00",
    status: "Confirmed",
    price: 25,
    notes: "Custom cherry art",
  },
  {
    id: "b4",
    customerId: "c6",
    customerName: "Chloe Davis",
    customerPhone: "+1 (650) 901-7788",
    serviceId: "s2",
    serviceName: "Organic Detox Pedicure",
    staffId: "st3",
    staffName: "Lily Smith",
    dateTime: "2026-06-19T14:30:00",
    status: "Confirmed",
    price: 55,
  },
  {
    id: "b5",
    customerId: "c3",
    customerName: "Sarah Miller",
    customerPhone: "+1 (408) 223-9912",
    serviceId: "s3",
    serviceName: "Signature Combo (Mani + Pedi)",
    staffId: "st4",
    staffName: "Tommy Le",
    dateTime: "2026-06-19T16:00:00",
    status: "Pending",
    price: 85,
  },
  {
    id: "b6",
    customerId: "c7",
    customerName: "Sophia Martinez",
    customerPhone: "+1 (408) 334-0012",
    serviceId: "s9",
    serviceName: "Gel Polish Color Change",
    staffId: "st5",
    staffName: "Tina Pham",
    dateTime: "2026-06-19T17:30:00",
    status: "Pending",
    price: 25,
  },
];

export const INITIAL_TRANSACTIONS: Transaction[] = [
  { id: "t1", bookingId: "b1", customerId: "c1", customerName: "Jenny Nguyen", paymentMethod: "Card", amount: 45, tipAmount: 10, staffId: "st1", dateTime: "2026-06-19T09:55:00" },
  { id: "t2", bookingId: "b2", customerId: "c2", customerName: "Tiffany Cooper", paymentMethod: "Apple Pay", amount: 65, tipAmount: 15, staffId: "st2", dateTime: "2026-06-19T11:45:00" },
  // Historical transactions
  { id: "t3", customerId: "c3", customerName: "Sarah Miller", paymentMethod: "Cash", amount: 55, tipAmount: 10, staffId: "st4", dateTime: "2026-06-18T14:20:00" },
  { id: "t4", customerId: "c4", customerName: "David Vu", paymentMethod: "Card", amount: 85, tipAmount: 15, staffId: "st3", dateTime: "2026-06-18T16:40:00" },
  { id: "t5", customerId: "c1", customerName: "Jenny Nguyen", paymentMethod: "Card", amount: 45, tipAmount: 8, staffId: "st1", dateTime: "2026-06-17T11:15:00" },
  { id: "t6", customerId: "c6", customerName: "Chloe Davis", paymentMethod: "Apple Pay", amount: 120, tipAmount: 25, staffId: "st3", dateTime: "2026-06-16T15:30:00" },
];

export const INITIAL_INVENTORY: InventoryItem[] = [
  { id: "i1", name: "OPI Gel Base Coat - 0.5 oz", category: "Gel Color", stockLevel: 14, minStockLevel: 5, unit: "bottles", supplier: "OPI Direct" },
  { id: "i2", name: "OPI Gel Top Coat - 0.5 oz", category: "Gel Color", stockLevel: 12, minStockLevel: 5, unit: "bottles", supplier: "OPI Direct" },
  { id: "i3", name: "DND Gel Polish #143 (Nude Peach)", category: "Gel Color", stockLevel: 3, minStockLevel: 4, unit: "bottles", supplier: "DND Distributor" }, // Low Stock!
  { id: "i4", name: "DND Gel Polish #552 (Soft Pink)", category: "Gel Color", stockLevel: 1, minStockLevel: 4, unit: "bottles", supplier: "DND Distributor" }, // Low Stock!
  { id: "i5", name: "Mia Secret Acrylic Powder - Clear 4oz", category: "Acrylic Powder", stockLevel: 6, minStockLevel: 3, unit: "jars", supplier: "Mia Secret Co" },
  { id: "i6", name: "Acetone Pure 100% - 1 Gallon", category: "Chemicals", stockLevel: 2, minStockLevel: 2, unit: "jugs", supplier: "Salon Centric" },
  { id: "i7", name: "Foil Nail Art Rolls (Chrome)", category: "Accessories", stockLevel: 15, minStockLevel: 5, unit: "boxes", supplier: "Nail Supply World" },
  { id: "i8", name: "Sanitizer Disinfectant Tablets", category: "Tools", stockLevel: 80, minStockLevel: 100, unit: "tablets", supplier: "Salon Centric" }, // Low Stock!
];

export const INITIAL_SMS_LOGS: SMSLog[] = [
  { id: "sms1", customerName: "Jenny Nguyen", phone: "+1 (650) 441-2091", type: "Reminder 24h", message: "Hi Jenny, this is a reminder for your Premium Gel Manicure with Amber tomorrow Fri Jun 19 at 9:00 AM. Pls reply C to confirm. NailOS Salon.", status: "Sent", sentAt: "2026-06-18T09:00:00" },
  { id: "sms2", customerName: "Tiffany Cooper", phone: "+1 (650) 321-1182", type: "Booking Confirmed", message: "Hi Tiffany, your appointment for Acrylic Full Set with Johnny on Fri Jun 19 at 10:30 AM has been confirmed! NailOS Salon.", status: "Sent", sentAt: "2026-06-18T10:30:00" },
  { id: "sms3", customerName: "Chloe Davis", phone: "+1 (650) 901-7788", type: "Birthday Wish", message: "Happy pre-birthday Chloe! Enjoy 15% off any service this week at NailOS Salon. Tap here to book: simplebook.ly/nailos", status: "Sent", sentAt: "2026-06-18T08:15:00" },
  { id: "sms4", customerName: "David Vu", phone: "+1 (415) 880-1288", type: "Miss You Offer", message: "Hi David, we haven't seen you in 30 days! Here is a $10 voucher for your next Organic Pedicure with us. Book at: simplebook.ly/nailos", status: "Sent", sentAt: "2026-06-15T12:00:00" },
];

export const INITIAL_COUPONS: Coupon[] = [
  { id: "cp1", code: "WELCOME10", discountType: "Percent", discountValue: 10, minSpend: 30, expiryDate: "2026-08-31", active: true },
  { id: "cp2", code: "BIRTHDAY15", discountType: "Percent", discountValue: 15, minSpend: 0, expiryDate: "2026-12-31", active: true },
  { id: "cp3", code: "MISSYOU10OFF", discountType: "Fixed", discountValue: 10, minSpend: 40, expiryDate: "2026-07-15", active: true },
  { id: "cp4", code: "SUMMER20", discountType: "Percent", discountValue: 20, minSpend: 60, expiryDate: "2026-07-31", active: true },
];
